encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("search", views.search, name="search"),
    path("random", views.random, name="random"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from random import randint, choice

from . import util

class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title of Entry")
    body = forms.CharField(widget=forms.Textarea(attrs={"style":"height:30em;"}))

class EditEntryForm(forms.Form):
    title = forms.CharField(widget=forms.HiddenInput())
    body = forms.CharField(widget=forms.Textarea(attrs={"style":"height:30em;"}))

def index(request):
    if request.method == "POST":

        result = request.POST["q"]
        if util.get_entry(result) == None:
            result_list = util.query(result)
            return render(request, "encyclopedia/index.html", {
                "entries" : result_list
            })
        else:
            return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': result}))
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })

def wiki(request, title):
    return render(request, "encyclopedia/wiki.html", {
        "title": util.Markdown(util.get_entry(title.upper())),
        "title_raw": title
    })

def new(request):
    ''' render new.html '''
    if request.method == "POST":
        ''' do something '''
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            print(title)
            body = form.cleaned_data["body"]
            if util.get_entry(title) != None:
                return HttpResponse("Sorry, Entry under this title already exists!")
            util.save_entry(title, body)
            return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': title}))


    edit = None
    return render(request, "encyclopedia/new.html", {
        "edit": edit,
        "form": NewEntryForm()
    })
    

def edit(request, title):
    ''' render edit or just pass args to new.html '''
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            body = form.cleaned_data["body"]
            util.save_entry(title, body)
            return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': title}))

    return render(request, "encyclopedia/edit.html", {
        "form": EditEntryForm(initial = {"body" : util.get_entry(title), "title" : title}),
        "title": title
    })

def random(request):
    ''' function that pulls a random entry and passes into
        wiki'''
    entry_list = util.list_entries()
    num = randint(0, 5)
    return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': choice(entry_list)}))

def search(request):
    ''' function that returns list of entries
        that match with request or 1 entry or none '''
    return HttpResponse("ugui")

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>{{title}}</h1>
    <form action="{% url 'encyclopedia:edit' title=title %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-sm">
            <div>{{field}}</div>
        </div class="form-group col-sm">
        {% endfor %}
        <div class="col-sm">
            <input type="submit" name="save" value="save">
        </div>
    </form>
        


{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' title=entry %}">{{ entry }}</a></li>
            {% empty%}
            <p> No matching results were found!</p>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>Create a New Entry</h1>
    <form action="{% url 'encyclopedia:new' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group col-sm">
            {{field.label}}
            <div>{{field}}</div>
        </div class="form-group col-sm">
        {% endfor %}
        <div class="col-sm">
            <input type="submit" name="save" value="save">
        </div>
    </form>
        


{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Entry
{% endblock %}

{% block body %}
    {% if title != None %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <a class="edit_link" href="{% url 'encyclopedia:edit' title=title_raw %}">edit entry</a>
            </div>
        </div>
    </div>
    <div class=container>

        
        {{title|safe}}
       
    {% else %}
        <p>No entries exist by that title!</p>
    {% endif %}
</div>


{% endblock %}